### ISSUE TITLE
"IndexError: list index out of range when receiving SMS with sms2mqtt"  

### ISSUE THREAD

**Issue by ravindrajob** [Domochip/sms2mqtt#16]
## Environment  
  
- sms2mqtt version: 1.4.6  
- Gammu version: 1.41.0  
- Python-gammu version: 3.2  
- Device: Qualcomm, Inc. Siemens SG75  
- Docker-compose configuration:  
  
```yaml  
sms2mqtt:  
    container_name: sms2mqtt  
    image: domochip/sms2mqtt  
    devices:  
    - /dev/serial/by-id/usb-Qualcomm__Incorporated_Qualcomm_CDMA_Technologies_MSM_864319031594962-if01-port0:/dev/mobile  
    environment:  
    - PIN=1234  
    - HOST=172.0.0.1  
    - PORT=1883  
    - PREFIX=sms2mqtt  
    - CLIENTID=sms2mqttclid  
    - USER=USER_mqtt  
    - PASSWORD=MDP  
```

# Description
 
Hello, i encountered an "IndexError: list index out of range" error while running sms2mqtt. The error seems to be related to the following line in sms2mqtt.py

```console
message = {"datetime":str(sms[0]['DateTime']), "number":sms[0]['Number'], "text":decodedsms['Entries'][0]['Buffer']}  
```

The script was working without any issues for several weeks, but suddenly stopped working.

I can still send SMS using Gammu with the following command:

```console
gammu sendsms TEXT 0600000000 -text "Ceci est un test"  
```
I have also tried different environment variables in my docker-compose configuration, but the problem persists.

```console
sms2mqtt    | 19:13:49: ===== sms2mqtt v1.4.6 =====  
sms2mqtt    | 19:13:53: Gammu runtime: v1.41.0  
sms2mqtt    | 19:13:53: Python-gammu runtime: v3.2  
sms2mqtt    | 19:13:53: Manufacturer: Qualcomm  
sms2mqtt    | 19:13:53: IMEI: **HIDE**
sms2mqtt    | 19:13:53: SIMIMSI: +**HIDE**  
sms2mqtt    | 19:13:53: Gammu initialized  
sms2mqtt    | Traceback (most recent call last):  
sms2mqtt    |   File "/app/sms2mqtt.py", line 265, in <module>  
sms2mqtt    |     loop_sms_receive()  
sms2mqtt    |   File "/app/sms2mqtt.py", line 116, in loop_sms_receive  
sms2mqtt    |     message = {"datetime":str(sms[0]['DateTime']), "number":sms[0]['Number'], "text":decodedsms['Entries'][0]['Buffer']}  
sms2mqtt    | IndexError: list index out of range  
sms2mqtt exited with code 1  

```

Any idea  ? :)

Regards
